//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeEssta.Mappers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class TakeEsstaMappers : global::System.Configuration.ApplicationSettingsBase {
        
        private static TakeEsstaMappers defaultInstance = ((TakeEsstaMappers)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TakeEsstaMappers())));
        
        public static TakeEsstaMappers Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-BJ4OQ4G\\SQLEXPRESS01;Initial Catalog=TakeEssta;Integrated Sec" +
            "urity=True\r\n")]
        public string ConnectionsString {
            get {
                return ((string)(this["ConnectionsString"]));
            }
            set {
                this["ConnectionsString"] = value;
            }
        }
    }
}
